DROP SCHEMA IF EXISTS amanager;

CREATE SCHEMA amanager
  DEFAULT CHARACTER SET utf8;

USE amanager;

CREATE TABLE USER (
  ID       BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(64) NOT NULL UNIQUE,
  PASSWORD VARCHAR(64) NOT NULL,
  ENABLED  BOOLEAN     NOT NULL,
  ADMIN    BOOLEAN     NOT NULL,
  CONSTRAINT USER_USERNAME_UNIQUE UNIQUE (USERNAME)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

INSERT INTO USER (USERNAME, PASSWORD, ENABLED, ADMIN) VALUES ('admin', 'admin', b'1', b'1');

CREATE TABLE PERMISSION (
  ID          BIGINT       NOT NULL PRIMARY KEY AUTO_INCREMENT,
  TYPE        VARCHAR(64)  NOT NULL,
  DESCRIPTION VARCHAR(256) NOT NULL
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE PERMISSIONS_USERS (
  PERMISSION BIGINT NOT NULL,
  USER       BIGINT NOT NULL,
  PRIMARY KEY (PERMISSION, USER),
  CONSTRAINT FK_PERMISSIONS_USERS_PERMISSION FOREIGN KEY (PERMISSION) REFERENCES PERMISSION (ID),
  CONSTRAINT FK_PERMISSIONS_USERS_USER FOREIGN KEY (USER) REFERENCES USER (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

INSERT INTO PERMISSION (TYPE, DESCRIPTION) VALUES ('ADMIN', 'Permessi amministratore');

INSERT INTO PERMISSIONS_USERS (PERMISSION, USER) VALUES ((SELECT p.ID
                                                          FROM PERMISSION p
                                                          WHERE p.TYPE = 'ADMIN'), (SELECT u.ID
                                                                                    FROM USER u
                                                                                    WHERE u.USERNAME = 'ADMIN'));

CREATE TABLE MUNICIPALITY (
  ID            BIGINT       NOT NULL PRIMARY KEY AUTO_INCREMENT,
  BELFIORE_CODE VARCHAR(4)   NOT NULL,
  NAME          VARCHAR(256) NOT NULL,
  CHIEF_TOWN    BOOLEAN      NOT NULL             DEFAULT FALSE,
  PROVINCE      VARCHAR(2)   NOT NULL,
  ZIP           VARCHAR(5)   NOT NULL,
  CONSTRAINT MUNICIPALITY_BELFIORE_CODE_UNIQUE UNIQUE (BELFIORE_CODE)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE SUBSCRIBER (
  ID              BIGINT       NOT NULL PRIMARY KEY AUTO_INCREMENT,
  VAT_CODE        VARCHAR(16)  NOT NULL,
  DOCUMENT_TYPE   VARCHAR(32),
  DOCUMENT_NUMBER VARCHAR(32),
  PHONE           VARCHAR(32)  NOT NULL,
  EMAIL           VARCHAR(128),
  BIRTH_CITY      BIGINT       NOT NULL,
  BIRTH_DATE      DATE         NOT NULL,
  CITY            BIGINT       NOT NULL,
  ADDRESS         VARCHAR(256) NOT NULL,
  SUSPENDED       BOOLEAN      NOT NULL,
  CONSTRAINT SUBSCRIBER_VAT_CODE_UNIQUE UNIQUE (VAT_CODE),
  CONSTRAINT SUBSCRIBER_DOCUMENT_UNIQUE UNIQUE (DOCUMENT_TYPE, DOCUMENT_NUMBER),
  CONSTRAINT FK_SUBSCRIBER_BIRTH_CITY FOREIGN KEY (BIRTH_CITY) REFERENCES MUNICIPALITY (ID),
  CONSTRAINT FK_SUBSCRIBER_CITY FOREIGN KEY (CITY) REFERENCES MUNICIPALITY (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE SUBSCRIBER_CARD (
  ID         BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CODE       VARCHAR(8)  NOT NULL,
  TYPE       VARCHAR(32) NOT NULL,
  VALID_FROM DATE        NOT NULL,
  VALID_TO   DATE,
  SUBSCRIBER BIGINT      NOT NULL,
  CONSTRAINT SUBSCRIBER_CARD_CODE_UNIQUE UNIQUE (CODE),
  CONSTRAINT FK_SUBSCRIBER_CARD_SUBSCRIBER FOREIGN KEY (SUBSCRIBER) REFERENCES SUBSCRIBER (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE SUBSCRIBER_FEE (
  ID         BIGINT        NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CARD       BIGINT        NOT NULL,
  AMOUNT     DECIMAL(8, 2) NOT NULL,
  VALID_FROM DATE          NOT NULL,
  VALID_TO   DATE          NOT NULL,
  CONSTRAINT FK_SUBSCRIBER_FEE_CARD FOREIGN KEY (CARD) REFERENCES SUBSCRIBER_CARD (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

ALTER TABLE SUBSCRIBER
  ADD FIRST_NAME VARCHAR(32) NOT NULL
  AFTER DOCUMENT_NUMBER;

ALTER TABLE SUBSCRIBER
  ADD LAST_NAME VARCHAR(32) NOT NULL
  AFTER FIRST_NAME;

ALTER TABLE SUBSCRIBER_CARD
  CHANGE CODE CARD_NUMBER VARCHAR(8) NOT NULL;

ALTER TABLE SUBSCRIBER_CARD
  DROP INDEX SUBSCRIBER_CARD_CODE_UNIQUE;

ALTER TABLE SUBSCRIBER_CARD
  ADD CONSTRAINT SUBSCRIBER_CARD_CARD_NUMBER_UNIQUE UNIQUE (CARD_NUMBER);

ALTER TABLE SUBSCRIBER
  ADD CONSTRAINT SUBSCRIBER_EMAIL_UNIQUE UNIQUE (EMAIL);

ALTER TABLE SUBSCRIBER
  ADD CONSTRAINT SUBSCRIBER_PHONE_UNIQUE UNIQUE (PHONE);

ALTER TABLE SUBSCRIBER
  ADD REGISTRATION_DATE DATE NOT NULL
  AFTER ID;

ALTER TABLE SUBSCRIBER_CARD
  ADD CREATED_AT DATE NOT NULL
  AFTER TYPE;

ALTER TABLE SUBSCRIBER_CARD
  CHANGE VALID_TO DISABLED_AT DATE;

CREATE TABLE SEQUENCE (
  ID    BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME  VARCHAR(64) NOT NULL,
  VALUE BIGINT      NOT NULL,
  CONSTRAINT SEQUENCE_NAME_UNIQUE UNIQUE (NAME)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

ALTER TABLE SUBSCRIBER
  ADD GENDER VARCHAR(1) NOT NULL
  AFTER BIRTH_DATE;

CREATE TABLE CREDIT_NOTE (
  ID       BIGINT        NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ADDED_AT TIMESTAMP     NOT NULL,
  CAUSAL   VARCHAR(32)   NOT NULL,
  AMOUNT   DECIMAL(8, 2) NOT NULL,
  NOTES    VARCHAR(256)                       DEFAULT NULL
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

ALTER TABLE SUBSCRIBER_FEE
  ADD CREDIT_NOTE BIGINT NOT NULL
  AFTER AMOUNT;

ALTER TABLE SUBSCRIBER_FEE
  DROP COLUMN AMOUNT;

ALTER TABLE SUBSCRIBER_FEE
  ADD CONSTRAINT FK_SUBSCRIBER_CARD_CREDIT_NOTE FOREIGN KEY (CREDIT_NOTE) REFERENCES CREDIT_NOTE (ID);

CREATE TABLE FEE_CONFIG (
  ID            BIGINT        NOT NULL PRIMARY KEY AUTO_INCREMENT,
  TYPE          VARCHAR(32)   NOT NULL,
  TIME_INTERVAL VARCHAR(32)   NOT NULL,
  AMOUNT        DECIMAL(8, 2) NOT NULL,
  ADDED_AT      TIMESTAMP     NOT NULL,
  REMOVED_AT    TIMESTAMP     NULL                 DEFAULT NULL
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

INSERT INTO FEE_CONFIG (TYPE, TIME_INTERVAL, AMOUNT, ADDED_AT)
VALUES ('SYMPATHIZER', 'ANNUAL', '5.00', CURRENT_TIMESTAMP());
INSERT INTO FEE_CONFIG (TYPE, TIME_INTERVAL, AMOUNT, ADDED_AT)
VALUES ('SUPPORTER', 'MONTHLY', '10.00', CURRENT_TIMESTAMP());

ALTER TABLE SUBSCRIBER_FEE
  ADD FEE_CONFIG BIGINT NOT NULL
  AFTER CARD;

ALTER TABLE SUBSCRIBER_FEE
  ADD CONSTRAINT FK_SUBSCRIBER_CARD_FEE_CONFIG FOREIGN KEY (FEE_CONFIG) REFERENCES FEE_CONFIG (ID);

CREATE TABLE RAW_PRODUCT (
  ID       BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME     VARCHAR(64) NOT NULL,
  TYPE     VARCHAR(32) NOT NULL,
  UM       VARCHAR(6)  NOT NULL,
  ADDED_AT TIMESTAMP   NOT NULL,
  CONSTRAINT RAW_PRODUCT_NAME_UNIQUE UNIQUE (NAME)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE EXPENSE_NOTE (
  ID          BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CREDIT_NOTE BIGINT,
  CONSTRAINT FK_EXPENSE_NOTE_CREDIT_NOTE FOREIGN KEY (CREDIT_NOTE) REFERENCES CREDIT_NOTE (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE RAW_PRODUCT_REGISTRY (
  ID           BIGINT        NOT NULL PRIMARY KEY AUTO_INCREMENT,
  EXPENSE_NOTE BIGINT        NOT NULL,
  RAW_PRODUCT  BIGINT        NOT NULL,
  QUANTITY     DECIMAL(8, 2) NOT NULL,
  AMOUNT       DECIMAL(8, 2) NOT NULL,
  ADDED_AT     TIMESTAMP     NOT NULL,
  OVER         BOOLEAN       NOT NULL,
  OVER_AT      TIMESTAMP     NULL                 DEFAULT NULL,
  CONSTRAINT FK_RAW_PRODUCT_REGISTRY_EXPENSE_NOTE FOREIGN KEY (EXPENSE_NOTE) REFERENCES EXPENSE_NOTE (ID),
  CONSTRAINT FK_RAW_PRODUCT_REGISTRY_RAW_PRODUCT FOREIGN KEY (RAW_PRODUCT) REFERENCES RAW_PRODUCT (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE PRODUCT (
  ID         BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  TYPE       VARCHAR(32) NOT NULL,
  NAME       VARCHAR(64) NOT NULL,
  ADDED_AT   TIMESTAMP   NOT NULL,
  REMOVED_AT TIMESTAMP   NULL                 DEFAULT NULL
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE PRICE (
  ID         BIGINT        NOT NULL PRIMARY KEY AUTO_INCREMENT,
  PRODUCT    BIGINT        NOT NULL,
  AMOUNT     DECIMAL(8, 2) NOT NULL,
  ADDED_AT   TIMESTAMP     NOT NULL,
  REMOVED_AT TIMESTAMP     NULL                 DEFAULT NULL,
  CONSTRAINT PRICE_UNIQUE UNIQUE (PRODUCT, ADDED_AT),
  CONSTRAINT FK_PRICE_PRODUCT FOREIGN KEY (PRODUCT) REFERENCES PRODUCT (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE INCOME_NOTE (
  ID          BIGINT    NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CREDIT_NOTE BIGINT    NOT NULL,
  OPENED_AT   TIMESTAMP NOT NULL,
  CLOSED_AT   TIMESTAMP NULL                 DEFAULT NULL,
  CONSTRAINT FK_INCOME_NOTE_CREDIT_NOTE FOREIGN KEY (CREDIT_NOTE) REFERENCES CREDIT_NOTE (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE PRODUCT_PART (
  ID          BIGINT        NOT NULL PRIMARY KEY AUTO_INCREMENT,
  RAW_PRODUCT BIGINT        NOT NULL,
  QUANTITY    DECIMAL(8, 2) NOT NULL,
  PRODUCT     BIGINT        NOT NULL,
  CONSTRAINT FK_PRODUCT_PART_RAW_PRODUCT FOREIGN KEY (RAW_PRODUCT) REFERENCES RAW_PRODUCT (ID),
  CONSTRAINT FK_PRODUCT_PART_PRODUCT FOREIGN KEY (PRODUCT) REFERENCES PRODUCT (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE SALE_ACT (
  ID          BIGINT    NOT NULL PRIMARY KEY AUTO_INCREMENT,
  PRODUCT     BIGINT    NOT NULL,
  INCOME_NOTE BIGINT    NOT NULL,
  ADDED_AT    TIMESTAMP NOT NULL,
  CONSTRAINT FK_SALE_ACT_PRODUCT FOREIGN KEY (PRODUCT) REFERENCES PRODUCT (ID),
  CONSTRAINT FK_SALE_ACT_INCOME_NOTE FOREIGN KEY (INCOME_NOTE) REFERENCES INCOME_NOTE (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE WITHDRAWAL_ORDER (
  ID                   BIGINT        NOT NULL PRIMARY KEY AUTO_INCREMENT,
  RAW_PRODUCT_REGISTRY BIGINT        NOT NULL,
  QUANTITY             DECIMAL(8, 2) NOT NULL,
  SALE_ACT             BIGINT        NOT NULL,
  CREATED_AT           TIMESTAMP     NOT NULL,
  CONSTRAINT FK_WITHDRAWAL_ORDER_RAW_PRODUCT_REGISTRY FOREIGN KEY (RAW_PRODUCT_REGISTRY) REFERENCES RAW_PRODUCT_REGISTRY (ID),
  CONSTRAINT FK_WITHDRAWAL_ORDER_SALE_ACT FOREIGN KEY (SALE_ACT) REFERENCES SALE_ACT (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;










